name=LiME-TM
version=1.0.0
author=wuhanstudio
maintainer=wuhanstudio
sentence=Lightning fast and Memory-Efficient Machine Learning model for MCU.
paragraph=Lightning fast and Memory-Efficient Machine Learning model for MCU.
category=Data Processing
url=https://github.com/wuhanstudio/tsetlin.idf
architectures=stm32
